{
  "openapi": "3.0.0",
  "info": {
    "title": "Next Swagger API Example",
    "version": "1.0"
  },
  "paths": {
    "/api/userinfo": {
      "get": {
        "summary": "Get user information",
        "description": "Retrieves details about a user.",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "User": {
        "type": "object",
        "required": [
          "id",
          "email"
        ],
        "properties": {
          "id": {
            "type": "number",
            "example": 1
          },
          "firstName": {
            "type": "string",
            "example": "John"
          },
          "lastName": {
            "type": "string",
            "example": "Doe"
          },
          "email": {
            "type": "string",
            "format": "email",
            "example": "johndoe@mail.co"
          }
        }
      }
    }
  },
  "tags": []
}